updated mr mysql templates

diff --git a/serverless/ecs/madisonreed/ephemeral-nested-infra/buildspec-deploy.yml b/serverless/ecs/madisonreed/ephemeral-nested-infra/buildspec-deploy.yml
--- a/serverless/ecs/madisonreed/ephemeral-nested-infra/buildspec-deploy.yml
+++ b/serverless/ecs/madisonreed/ephemeral-nested-infra/buildspec-deploy.yml
@@ -5,6 +5,7 @@ env:
     - IMAGE_TAG
     - MYSQL_IMAGE_TAG
     - MONGO_IMAGE_TAG
+    - SNAPSHOT_ID
 
 phases:
   install:
@@ -17,23 +18,32 @@ phases:
       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
       - IMAGE_TAG=${COMMIT_HASH:-latest}
 
-      - MYSQL_REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mysql-ephemeral
       - MONGO_REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mongo-ephemeral
 
-      # Check if mysql task definition exists (This build has deployed the env before)
-      - MYSQL_FULL_IMAGE_URI=$(aws ecs describe-task-definition --task-definition ${APP_NAME}-mysql --query "taskDefinition.containerDefinitions[?name=='mysql'].image" --output text 2>/dev/null || echo "")
-      # Extract the tag from the image URI if it exists
-      - |
-        if [[ "$MYSQL_FULL_IMAGE_URI" == *":"* ]]; then
-          MYSQL_IMAGE_TAG=$(echo $MYSQL_FULL_IMAGE_URI | sed 's/.*://')
-        else
-          # If the task definition does not exist or does not have a tag, get the latest image tag from ECR
-          echo "Task definition does not exist or no tag found. Fetching the latest MySQL image tag from ECR..."
-          MYSQL_REPO_NAME=mysql-ephemeral
-          MYSQL_IMAGE_TAG=$(aws ecr describe-images --repository-name ${MYSQL_REPO_NAME} --query 'sort_by(imageDetails,&imagePushedAt)[-1].imageTags[1]' --output text)
-        fi
-      - echo "MySQL Image Tag [ ${MYSQL_IMAGE_TAG} ]"
+      - STACK_NAME="${APP_NAME}-ephemeral"
+      - OUTPUT_KEY="mysqlEbsSnapshotId"
 
+        # Get the stack outputs
+      - SNAPSHOT_ID=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --query "Stacks[0].Outputs[?OutputKey=='$OUTPUT_KEY'].OutputValue" --output text 2>/dev/null)
+
+      - |
+        # Check if the describe-stacks command was successful
+        if [ $? -ne 0 ]; then
+            echo "Stack $STACK_NAME does not exist or there was an error fetching the stack details. Using Latest MySQL SnapshotId"
+            # Grab the latest snapshot
+            SNAPSHOT_ID=$(aws ec2 describe-snapshots --filters Name=tag-key,Values=ephemeral-mysql --query "Snapshots[].[SnapshotId,StartTime]" --output json | jq -r 'sort_by(.[1]) | last | .[0]')
+            echo "Using Latest MySQL EBS SnapshotId: $SNAPSHOT_ID"
+        else
+            # Check if the SnapshotId was found
+            if [ -z "$SNAPSHOT_ID" ]; then
+                echo "No output with key $OUTPUT_KEY found in stack $STACK_NAME."
+                # Grab the latest snapshot
+                SNAPSHOT_ID=$(aws ec2 describe-snapshots --filters Name=tag-key,Values=ephemeral-mysql --query "Snapshots[].[SnapshotId,StartTime]" --output json | jq -r 'sort_by(.[1]) | last | .[0]')
+                echo "Using Latest MySQL EBS SnapshotId: $SNAPSHOT_ID"
+            else
+                echo "SnapshotId found. Continuing to use the previous snapshot used: $SNAPSHOT_ID"
+            fi
+        fi
 
       # Do the same for Mongo
       - MONGO_FULL_IMAGE_URI=$(aws ecs describe-task-definition --task-definition ${APP_NAME}-mongo --query "taskDefinition.containerDefinitions[?name=='mongo'].image" --output text 2>/dev/null || echo "")
@@ -48,7 +58,6 @@ phases:
           MONGO_IMAGE_TAG=$(aws ecr describe-images --repository-name ${MONGO_REPO_NAME} --query 'sort_by(imageDetails,&imagePushedAt)[-1].imageTags[1]' --output text)
         fi
       - echo "Mongo Image Tag [ ${MONGO_IMAGE_TAG} ]"
-
 
       - echo Listing Source Files...
       # list all files by most recently modified in reverse order
@@ -82,12 +91,13 @@ phases:
               pSocketioEcrImageUri=${TOPHAT_REPOSITORY_URI}:${IMAGE_TAG} \
               pApiServerEcrImageUri=${APISERVER_REPOSITORY_URI}:${IMAGE_TAG} \
               pMongoEcrImageUri=${MONGO_REPOSITORY_URI}:${MONGO_IMAGE_TAG} \
-              pMysqlEcrImageUri=${MYSQL_REPOSITORY_URI}:${MYSQL_IMAGE_TAG} \
+              pMysqlEcrImageUri=mysql:8.0 \
+              pMysqlEbsSnapshotId=${SNAPSHOT_ID} \
               pPublicSubnetId1=subnet-0598f465e77230bd5 \
               pPublicSubnetId2=subnet-0d650820a97fa5ba3 \
               pR53HostedZoneId=Z0323068C9DQS081P13G \
               pR53HostedZoneName=dev.mdsnrdfd.com" \
-          --stack-name ${APP_NAME}-ephemeral \
+          --stack-name $STACK_NAME \
           --tags \
               CleanupDate=$(date -u -d "+10 days" '+%Y-%m-%dT%H:%M:%SZ') \
               ephemeral:app=${APP_NAME} \
